// Autogenerated by Thrift Compiler (0.9.1)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package serde

import (
	"fmt"
	"git.apache.org/thrift.git/lib/go/thrift"
	"math"
)

// (needed to ensure safety because of naive import list construction.)
var _ = math.MinInt32
var _ = thrift.ZERO
var _ = fmt.Printf

const SERIALIZATION_LIB = "serialization.lib"
const SERIALIZATION_CLASS = "serialization.class"
const SERIALIZATION_FORMAT = "serialization.format"
const SERIALIZATION_DDL = "serialization.ddl"
const SERIALIZATION_NULL_FORMAT = "serialization.null.format"
const SERIALIZATION_LAST_COLUMN_TAKES_REST = "serialization.last.column.takes.rest"
const SERIALIZATION_SORT_ORDER = "serialization.sort.order"
const SERIALIZATION_USE_JSON_OBJECTS = "serialization.use.json.object"
const FIELD_DELIM = "field.delim"
const COLLECTION_DELIM = "colelction.delim"
const LINE_DELIM = "line.delim"
const MAPKEY_DELIM = "mapkey.delim"
const QUOTE_CHAR = "quote.delim"
const ESCAPE_CHAR = "escape.delim"
const VOID_TYPE_NAME = "void"
const BOOLEAN_TYPE_NAME = "boolean"
const TINYINT_TYPE_NAME = "tinyint"
const SMALLINT_TYPE_NAME = "smallint"
const INT_TYPE_NAME = "int"
const BIGINT_TYPE_NAME = "bigint"
const FLOAT_TYPE_NAME = "float"
const DOUBLE_TYPE_NAME = "double"
const STRING_TYPE_NAME = "string"
const DATE_TYPE_NAME = "date"
const DATETIME_TYPE_NAME = "datetime"
const TIMESTAMP_TYPE_NAME = "timestamp"
const LIST_TYPE_NAME = "array"
const MAP_TYPE_NAME = "map"
const STRUCT_TYPE_NAME = "struct"
const UNION_TYPE_NAME = "uniontype"
const LIST_COLUMNS = "columns"
const LIST_COLUMN_TYPES = "columns.types"

var PrimitiveTypes map[string]bool
var CollectionTypes map[string]bool

func init() {
	PrimitiveTypes = map[string]bool{
		"void":      true,
		"boolean":   true,
		"tinyint":   true,
		"smallint":  true,
		"int":       true,
		"bigint":    true,
		"float":     true,
		"double":    true,
		"string":    true,
		"date":      true,
		"datetime":  true,
		"timestamp": true,
	}

	CollectionTypes = map[string]bool{
		"array": true,
		"map":   true,
	}

}
